"""Generate docs/demo.md — the three demos, captured from real runs.

    uv run python bench/demo.py

Every line in the README's demo blocks is copied from this file, never written by hand,
and a CI check enforces that they match. The three streams come from committed fixtures
with known ground truth, so the transcripts below are what the tool actually prints when
handed data whose answer we already know.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from bench.sim.generate import generate, read_manifest, spec_from_json  # noqa: E402
from benchlock.attribute.engine import decide  # noqa: E402
from benchlock.config import AttributionConfig  # noqa: E402
from benchlock.report.human import render_verdict_block  # noqa: E402

MANIFEST = ROOT / "tests" / "fixtures" / "streams" / "manifest.json"
OUT = ROOT / "docs" / "demo.md"
CONFIG = AttributionConfig(alpha=0.05, min_runs=8, min_obs=30, baseline_runs=8, target_shift=0.05)

DEMOS = [
    (
        "demo1-phantom-judge",
        "Demo 1 — the phantom regression",
        """\
A team's eval pass rate falls over two weeks. Their dashboard flags a regression and the
on-call engineer starts bisecting.

**Ground truth: the provider rotated the judge snapshot behind a stable model string. The
system under test was byte-identical throughout, and the rollback would have been pure
waste.**""",
        "`benchlock gate` exits **0**. A judge change must not fail your build.",
    ),
    (
        "demo2-real-regression",
        "Demo 2 — the real regression, correctly named",
        """\
The same pipeline. This time the system genuinely regressed, and the judge did not move.

**Ground truth: a system regression, with the judge held constant.**""",
        "`benchlock gate` exits **1**. This one should fail your build.",
    ),
    (
        "demo3-under-provisioned",
        "Demo 3 — the honest one, which is the point of the project",
        """\
The same real regression as Demo 2, from the same seed — but the anchor set was configured
at 40 items instead of the 200 that `benchlock plan` asked for.

Most tools would say "regression" here and be right by luck. Benchlock refuses, says why,
and says exactly what to change.

**A tool that is confidently wrong one time in ten is worse than useless in a CI gate,
because people learn to ignore it.**""",
        "`benchlock gate` exits **2** — a warning, not a failure, and not a verdict.",
    ),
]


def main() -> int:
    entries = {e["name"]: e for e in read_manifest(MANIFEST)}
    parts = [
        "<!-- GENERATED by bench/demo.py. Do not edit by hand. -->",
        "# The three demos",
        "",
        "Captured from real runs over committed fixture streams with known ground truth.",
        "Regenerate with `uv run python bench/demo.py`; CI checks that the README's blocks",
        "still match this file.",
        "",
    ]

    for name, title, preamble, footer in DEMOS:
        entry = entries[name]
        system, anchor = generate(spec_from_json(entry))
        attribution = decide(system, anchor, CONFIG)
        block = render_verdict_block(attribution)

        parts.extend(
            [
                f"## {title}",
                "",
                preamble,
                "",
                "```text",
                "$ benchlock verdict",
                block.rstrip("\n"),
                "```",
                "",
                footer,
                "",
                f"<sub>fixture `{name}`, ground truth `{entry['ground_truth']}`, "
                f"verdict `{attribution.verdict.value}` via rule `{attribution.rule_id}`</sub>",
                "",
                "---",
                "",
            ]
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT.relative_to(ROOT)}")
    for name, *_ in DEMOS:
        entry = entries[name]
        system, anchor = generate(spec_from_json(entry))
        attribution = decide(system, anchor, CONFIG)
        status = "OK" if _expected(name) == attribution.verdict.value else "MISMATCH"
        print(f"  {name:<26s} -> {attribution.verdict.value:<14s} [{status}]")
    return 0


def _expected(name: str) -> str:
    return {
        "demo1-phantom-judge": "judge",
        "demo2-real-regression": "system",
        "demo3-under-provisioned": "indeterminate",
    }[name]


if __name__ == "__main__":
    raise SystemExit(main())
