"""Markdown for a PR comment and for `RESULTS.md` fragments.

Rendered from the same `Attribution` the terminal block uses, so a PR comment and a
terminal cannot disagree about what happened.
"""

from __future__ import annotations

from benchlock.model.verdict import Attribution, Evidence, Provisioning, Verdict

_EMOJI = {
    Verdict.STABLE: "✅",
    Verdict.JUDGE: "🔧",
    Verdict.SYSTEM: "🔴",
    Verdict.BOTH: "🟠",
    Verdict.INDETERMINATE: "❓",
}

_HEADLINE = {
    Verdict.STABLE: "No change detected in either stream.",
    Verdict.JUDGE: "**The judge moved, not your system.** Do not roll back.",
    Verdict.SYSTEM: "**Your system moved, and the judge demonstrably did not.**",
    Verdict.BOTH: "**Both moved.** Benchlock will not separate them.",
    Verdict.INDETERMINATE: "**Cannot rule out the judge.** The anchor set is under-provisioned.",
}


def _row(name: str, value: float, threshold: float, crossed_at: int | None) -> str:
    state = f"crossed at run {crossed_at}" if crossed_at is not None else "not crossed"
    return f"| `{name}` | {value:,.1f} | {threshold:,.1f} | {state} |"


def _corrected_row(e: Evidence) -> str:
    state = "crossed" if e.corrected_crossed else "not crossed"
    return f"| `E_corrected` | {e.e_corrected:,.1f} | {e.threshold:,.1f} | {state} |"


def _interval(lower: float, upper: float) -> str:
    return f"`[{lower:+.3f}, {upper:+.3f}]`"


def render_markdown(attribution: Attribution, *, title: str = "Benchlock verdict") -> str:
    """A PR comment: the verdict, the two traces, the intervals and the provisioning."""
    e = attribution.evidence
    lines = [
        f"### {_EMOJI[attribution.verdict]} {title}: `{attribution.verdict.value}`",
        "",
        _HEADLINE[attribution.verdict],
        "",
        f"Anytime-valid at `alpha={attribution.alpha}` — this holds however many times you "
        "have looked at it.",
        "",
        "| process | e-value | threshold | status |",
        "|---|---:|---:|---|",
        _row("E_anchor", e.e_anchor, e.threshold, e.crossed_at_anchor),
        _row("E_system", e.e_system, e.threshold, e.crossed_at_system),
        # `crossed_at` is not recorded for the corrected process, but "not crossed" is a
        # claim, not a placeholder: printing it beside an e-value of 476 against a
        # threshold of 40 contradicts both the number on the same row and the terminal
        # block. Say whether it crossed, and stay silent about when.
        _corrected_row(e),
        "",
        "| shift | confidence sequence |",
        "|---|---|",
        f"| anchor (the judge) | {_interval(e.anchor_shift.lower, e.anchor_shift.upper)}"
        + (" **(lower bound — ran past the band)**" if e.anchor_shift_saturated else "")
        + " |",
        f"| system (raw) | {_interval(e.system_shift.lower, e.system_shift.upper)}"
        + (" **(lower bound — ran past the band)**" if e.system_shift_saturated else "")
        + " |",
        "| system, judge removed | "
        + _interval(e.corrected_shift.lower, e.corrected_shift.upper)
        + " |",
        "",
        "**Why**",
        "",
    ]
    lines.extend(f"- {reason}" for reason in attribution.reasons)
    lines.append("")

    if e.anchor_n:
        mark = "✅" if e.provisioning is Provisioning.ADEQUATE else "⚠️"
        lines.append(
            f"{mark} **Anchor provisioning: {e.provisioning.value}** — "
            f"{e.anchor_n} items, {e.n_anchor_runs} monitored runs, smallest detectable "
            f"judge shift `{e.min_detectable_judge_shift:.3f}`."
        )
        lines.append("")

    if e.judge_pin_delta:
        lines.append(f"Judge pin fields that moved: `{'`, `'.join(e.judge_pin_delta)}`.")
        lines.append("")

    if attribution.next_command:
        lines.extend(["**Next**", "", "```sh", attribution.next_command, "```", ""])

    lines.append(
        f"<sub>rule `{attribution.rule_id}` · epoch {e.epoch} · "
        f"{e.n_runs} runs · generated by `benchlock report`</sub>"
    )
    return "\n".join(lines) + "\n"
