#!/usr/bin/env python3
"""Generate README.md, with every number read from a committed run.

Hand-writing the README is how an invented number gets in. The prose lives here; the
figures are read from `bench/results/` and the demo block is lifted verbatim from
`docs/demo.md`, so the three can never drift apart.

    uv run python scripts/gen_readme.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "bench" / "results"
OUT = ROOT / "README.md"


def load(name: str) -> dict:
    path = RESULTS / name
    if not path.exists():
        raise SystemExit(f"missing {path.relative_to(ROOT)} — run the benchmarks first")
    return json.loads(path.read_text())


def demo_block(section: str) -> str:
    text = (ROOT / "docs" / "demo.md").read_text()
    match = re.search(rf"## {re.escape(section)}.*?(```text\n.*?\n```)", text, re.S)
    if match is None:
        raise SystemExit(f"could not find {section!r} in docs/demo.md — run bench/demo.py")
    return match.group(1)


def main() -> int:
    headline = load("sim-headline.json")
    attacks = load("adversarial-latest.json")

    stable = headline["stable"]
    judge = headline["judge"]
    seeds = headline["seeds"]
    b1_fa = stable["B1-peeking-t-test"]["alarm_rate"]
    b2_fa = stable["B2-bonferroni-t-test"]["alarm_rate"]
    b6_fa = stable["B6-benchlock"]["alarm_rate"]
    b1_wrong = judge["B1-peeking-t-test"]["verdicts"].get("regression", 0) / seeds
    b5_wrong = judge["B5-benchlock-no-anchor"]["verdicts"].get("regression", 0) / seeds
    b6_right = judge["B6-benchlock"]["verdicts"].get("judge", 0) / seeds

    by_strategy = {r["strategy"]: r for r in attacks["rows"]}
    attack_rows = "\n".join(
        f"| {r['strategy']} | {r['description']} | **{r['failure_rate']:.0%}** |"
        for r in sorted(attacks["rows"], key=lambda r: -r["failure_rate"])
    )
    evasion = by_strategy["7.1 anchor evasion"]["failure_rate"]

    OUT.write_text(f"""<!-- GENERATED by scripts/gen_readme.py. Do not edit by hand. -->
# Benchlock

**Your eval score dropped. Benchlock tells you whether your system regressed or the judge
changed underneath you — with a guarantee that survives looking every day.**

A *bench mark* is a surveyor's fixed reference, cut into stone so every other measurement
can be taken from it. Benchlock cuts one into your eval pipeline and locks it, so that when
a number moves you can tell whether the wall shifted or the ruler did.

---

## The phantom regression

A team's eval pass rate falls over two weeks. The dashboard flags a regression and the
on-call engineer starts bisecting.

{demo_block("Demo 1 — the phantom regression")}

Ground truth: the provider rotated the judge snapshot behind a stable model string. The
system under test was byte-identical throughout. **The rollback would have been pure waste,
and `benchlock gate` exits 0 — a judge change must not fail your build.**

Two more demos, including the one this project actually exists for, are in
[docs/demo.md](docs/demo.md).

---

## Two numbers

### 1. Peeking

Over {seeds} drift-free streams, each inspected after **every one** of
{headline["monitored_runs"]} runs, at `alpha={headline["alpha"]}`:

| method | raises at least one false alarm on |
|---|---:|
| t-test re-run every run | **{b1_fa:.1%}** of healthy pipelines |
| the same, Bonferroni-corrected | **{b2_fa:.1%}** |
| **Benchlock** | **{b6_fa:.1%}** |

Peeking is not a misuse of the t-test here — it *is* the workflow. CI runs on every commit
and someone looks at the number every time. A test with a fixed alpha, re-run at every
accumulating observation, has no type-I error control at all.

### 2. Attribution

The same pipeline, with the *judge* shifted and the system under test byte-identical:

| method | what it concludes |
|---|---|
| t-test re-run every run | "regression", **{b1_wrong:.0%}** of the time |
| Benchlock **without** an anchor set | "regression", **{b5_wrong:.0%}** of the time |
| **Benchlock** | `judge`, **{b6_right:.0%}** of the time |

Single-stream methods have no attribution available to them. Watching one number, the only
conclusion reachable is "it moved" — a structural fact about the method, not a criticism of
anyone using it. The middle row is Benchlock with its own control group removed, which is
the honest measure of what the anchor set costs and buys.

Full tables, including every baseline and the cases where Benchlock loses, are in
[RESULTS.md](RESULTS.md).

---

## [Attacks that work against Benchlock](docs/threat-model.md)

Measured, not estimated. This is near the top rather than in an appendix because you should
know what beats it before you install it.

| attack | what it does | failure rate |
|---|---|---:|
{attack_rows}

**Anchor evasion is the fundamental limitation.** A judge change confined to a region your
anchor set does not cover is invisible: the system stream moves, the anchor stream does
not, and Benchlock says `system` — a confident, wrong rollback recommendation. Coverage is
measured and warned about. It is never guaranteed. Reproduce with
`{attacks["command"]}`.

---

## The mechanism, in three lines

![Two streams, one judge, four answers](docs/assets/mechanism.svg)

Hold a frozen anchor set that the system under test never touches, and have the judge
re-score it every run.

- the anchor score moved ⇒ **only the judge can have moved it**
- the system score moved and the anchor did not ⇒ **the system moved**
- both moved ⇒ **confounded**, and Benchlock says so rather than picking

That is a difference-in-differences design where the anchor set is the control group and
the judge is the shared time effect. It is not clever; it works because it is deterministic
and needs no model to adjudicate it. Wrapping it in anytime-valid sequential tests is what
makes the verdict survive daily peeking.

**No human labels are required.** Attribution needs judge *stability*, not judge *validity*
— so a snapshot of the judge's own scores is a sufficient control. The argument is written
out in [docs/identification.md](docs/identification.md).

---

## Install

```sh
uv tool install benchlock
```

```sh
benchlock init                                   # detects promptfoo / Inspect AI / DeepEval
benchlock baseline --anchors your-suite.jsonl    # freezes anchors, measures the noise floor
benchlock plan --target-shift 0.05               # how many anchors you actually need
benchlock observe results.jsonl --rescore-anchors
benchlock gate                                   # the last line of your CI job
```

Exit codes: `0` for `stable` and `judge`, `1` for `system` and `both`, `2` for
`indeterminate`. A judge change does not fail your build; it tells you to re-baseline.

There is a [GitHub Action](.github/actions/benchlock/action.yml) that runs the whole
sequence and posts the verdict as a PR comment.

---

## The five verdicts

| verdict | meaning | CI |
|---|---|---|
| `stable` | neither process has crossed | pass |
| `judge` | the judge moved | pass — re-baseline, do not roll back |
| `system` | the system moved, and the judge demonstrably did not | **fail** |
| `both` | both moved; the correction does not explain the system's move | **fail** |
| `indeterminate` | the anchor set could not rule out the judge | warn |

`indeterminate` is the one that makes the other four mean anything. Without it, a tool
whose anchor set was too small to rule out the judge would still say `system`, and be right
by luck often enough to be believed. **A tool that is confidently wrong one time in ten is
worse than useless in a CI gate, because people learn to ignore it.**

---

## Prior art

**["Who Drifted: the System or the Judge? Anytime-Valid Attribution in LLM Evaluation
Pipelines" (arXiv 2606.15474, June 2026)](https://arxiv.org/abs/2606.15474) states this
problem, proposes the anchor-set and e-process construction, and reports a three-way
verdict.** It is the intellectual source for this project. It is a solo-authored,
unaffiliated preprint with no public code and no third-party reproduction; its anchor sets
are human-labeled, which is a multi-week adoption cost; it has no state for "I cannot
tell"; and it gives no method for sizing the anchor set.

**The mathematics is not ours.** Ville's inequality (1939) is the entire guarantee. Howard,
Ramdas, McAuliffe & Sekhon gave the time-uniform bounds and confidence sequences;
Waudby-Smith & Ramdas gave the betting construction we use, and their `confseq` package is
our test oracle; Grünwald, de Heide & Koolen framed e-values as the right object; Shin,
Ramdas & Rinaldo's e-detectors are the change-detection primitive. None of it knows what an
LLM judge is.

**Prediction-powered inference** (Angelopoulos et al., *Science* 2023) is the closest
statistical cousin, and `human` anchor mode is essentially PPI applied to judge scores.

**LLM drift tools** (`llm-drift`, `driftmonitor-ai`, `dedrift`) do embedding and output
diffing with classical fixed-sample tests; `dedrift` paywalls its e-process layer. **None of
them attribute.** They tell you a number moved, which is the easy half.

**Eval platforms** (promptfoo, DeepEval, Braintrust, LangSmith, Phoenix, Langfuse, Weave,
Evidently, RAGAS, Inspect AI) compute, store and compare scores, some with threshold alerts.
**None is valid under repeated looking, and none has a control group.** They are the
substrate Benchlock plugs into, not competitors — there are adapters for several of them.

**Classical change detection** (CUSUM, ADWIN, DDM) detects single-stream change with no
notion of *which of two causes* produced it. They are baselines in [RESULTS.md](RESULTS.md),
not prior art we extend.

**What is ours:** the first installable implementation of judge-versus-system attribution;
the observation that attribution needs judge stability rather than validity, which removes
the labelling requirement entirely; and the provisioning rule plus the `indeterminate`
verdict, which together are the difference between a guarantee and a decoration.

---

## Known limitations

- **Anchor evasion is the fundamental limitation.** A judge change confined to a region your
  anchor set does not cover is invisible — measured at **{evasion:.0%}** in the worst case.
  Coverage is measured and warned about; it is never guaranteed.
- **Benchlock tells you *that* the judge changed, never *why*.** A provider rotation and a
  teammate's rubric edit are indistinguishable unless you declared one of them.
- **`frozen-self` anchors detect judge instability, not judge invalidity.** A judge that was
  always wrong stays wrong and reads as stable. Benchlock does not claim your evals are
  correct.
- **Your own standards changing reads as permanent judge drift** until you re-baseline. The
  tool warns; it does not solve.
- **The guarantee is time-uniform, not instantaneous.** Anytime-valid tests detect *later*
  than invalid ones. That is the price, and it is measured in [RESULTS.md](RESULTS.md)
  rather than hidden.
- **A fixed suite is required.** If your eval inputs are sampled from shifting production
  traffic, score movement has a third cause Benchlock does not model — and the suite-hash
  check sees item ids, not item content, so it cannot catch every version of this.
- **Bounded scores only.** Rubrics must declare their range and stay inside it.
- **Needs a stream.** Nothing useful for a single run; `min_runs` defaults to 8 for a reason.
- **Nothing for pipelines with no LLM judge.** Programmatic scorers with no model in them do
  not drift, which is a good argument for using them where you can.
- **A judge that got noisier without changing its mean is not reported as a judge change.**
  The reasoning is in [docs/threat-model.md](docs/threat-model.md); a dedicated
  variance-change warning is not implemented.
- **Benchlock does not watch the judge's *refusal* rate**, only its scores. Measured
  against a real judge, editing the rubric alone raised the refusal rate 6.7x — and a
  refused item vanishes silently from the sample, so a score-only tool cannot see it.
  See [RESULTS.md](RESULTS.md).
- **A judge configuration change that moves refusals but not scores is invisible.** Raising
  the judge's reasoning effort tripled its refusal rate while barely moving the mean score,
  and Benchlock returned `stable` — one of six real-judge scenarios it gets wrong.
- **Single judge, single suite, single system.** Ensembles and portfolios are v2.

---

## Docs

- [The identification argument](docs/identification.md) — what is claimed, and the
  assumptions it rests on
- [Statistical guarantees](docs/statistical-guarantees.md) — what is guaranteed, what is
  not, and our own measured false-alarm rates
- [Provisioning](docs/provisioning.md) — how to size an anchor set, with worked examples
- [Threat model](docs/threat-model.md) — what breaks this
- [RESULTS.md](RESULTS.md) — every benchmark number, generated

## License

Apache-2.0.
""")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
