#!/usr/bin/env python3
"""Generate docs/launch.md — the launch artefacts, with numbers read from committed runs.

This document is the one that gets *posted*, so it is the last place an unmeasured number
should be allowed to survive. It was hand-written until its false-alarm figure and delay
ratio had drifted a full regeneration behind `bench/results/`, which is exactly the failure
`check_numbers.py` exists to prevent — except that check only covered README.md and
RESULTS.md, so the document aimed at the widest audience was the one nothing guarded.

    uv run python scripts/gen_launch.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "bench" / "results"
OUT = ROOT / "docs" / "launch.md"

#: The public repository. Referenced here rather than left as an ellipsis, because a
#: placeholder URL in the one document meant for posting is a defect, not a formality.
REPO_URL = "https://github.com/Poojan6216/benchlock"


def load(name: str) -> dict:
    path = RESULTS / name
    if not path.exists():
        raise SystemExit(f"missing {path.relative_to(ROOT)} — run the benchmarks first")
    return json.loads(path.read_text())


def main() -> int:
    headline = load("sim-headline.json")
    summary = load("summary.json")["aggregates"]
    attacks = load("adversarial-latest.json")
    nd = load("judge-nondeterminism.json")["rows"][0]

    seeds = headline["seeds"]
    b1_fa = headline["stable"]["B1-peeking-t-test"]["alarm_rate"]
    b6_fa = headline["stable"]["B6-benchlock"]["alarm_rate"]
    b1_wrong = headline["judge"]["B1-peeking-t-test"]["verdicts"].get("regression", 0) / seeds
    b6_right = headline["judge"]["B6-benchlock"]["verdicts"].get("judge", 0) / seeds
    ratio = summary["antiresult.delay_ratio"]
    b1_delay = summary["antiresult.b1_mean_delay"]
    b6_delay = summary["antiresult.b6_mean_delay"]
    attacks_that_work = sum(1 for r in attacks["rows"] if r["failure_rate"] > 0)
    n_attacks = len(attacks["rows"])

    OUT.write_text(f"""<!-- GENERATED by scripts/gen_launch.py. Do not edit by hand. -->
# Launch artefacts

Every number below is read from `bench/results/` by the generator, so this document cannot
drift behind the runs it quotes. If a figure here looks wrong, re-run the benchmark and
regenerate; do not edit the prose.

## The post

One number, one link, one honest caveat. No thread.

> Your eval dashboard flags a regression. You bisect for a week. The system never changed —
> the provider rotated the judge snapshot underneath you.
>
> I measured how often the standard approach gets this wrong. A t-test re-run on every CI
> commit raises a false alarm on **{b1_fa:.1%} of perfectly healthy pipelines**, and when
> only the judge moved it says "regression" **{b1_wrong:.0%} of the time**.
>
> Benchlock holds a frozen anchor set your system never touches, so if those scores move,
> only the judge can have moved them. **{b6_fa:.1%}** false alarms, and it names the judge
> **{b6_right:.0%}** of the time.
>
> The honest caveat: it detects a real regression about **{ratio:.1f}× slower** than the
> invalid test — {b6_delay:.1f} runs against {b1_delay:.1f}. That is the price of a
> guarantee that survives daily peeking, and it is in the results table, not a footnote.
>
> {attacks_that_work} of {n_attacks} attacks still beat it. Those are published too.
>
> {REPO_URL}

The alternative opening number, if the audience is closer to the models than to the CI
pipeline: **a judge at its most deterministic setting disagrees with itself
{nd["self_disagreement_rate"]:.1%} of the time.** Same identical question, one time in
{round(1 / nd["self_disagreement_rate"])} a different score. That one needs no setup.

## The terminal recording

30 seconds, Demo 1. Record with `asciinema rec`. The order matters and is not negotiable:
`plan` reads the noise floor that `baseline` measures, so running it earlier exits with an
error rather than a number.

```sh
benchlock init                                # detect the eval framework, write config
benchlock baseline --anchors suite.jsonl      # freeze the anchors, measure the noise floor
benchlock plan --target-shift 0.05            # how many anchors that target actually needs
benchlock observe results.jsonl --rescore-anchors
benchlock verdict                             # verdict=judge
benchlock gate; echo $?                       # 0 — a judge change does not fail your build
```

The beat to land: `verdict=judge` followed by exit code `0`. The tool telling you *not* to
act is the point.

## The diagram

[`docs/assets/mechanism.svg`](assets/mechanism.svg) — two streams, one judge, four answers,
with `indeterminate` outlined because it is the one that makes the other three mean
anything. Renders in both light and dark GitHub themes.

## What not to do

- No "enterprise-grade". No "revolutionise". The tool tells you which of two things moved;
  it does not make your evals correct.
- Do not lead with the false-alarm number alone. Lead with `indeterminate`, or with the
  {ratio:.1f}× delay. The interesting claim is that the tool refuses to answer when it
  cannot know, and that its honest cost is published.
- Do not quote a number from memory or from an older draft of this file. Every figure above
  is generated; `uv run python scripts/check_generated.py` fails if this document and its
  generator disagree.
- Credit the preprint (arXiv 2606.15474) in the first paragraph of any technical write-up.
  It got here first.
""")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
